name: Terraform Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'core/**' # Adjust this path to match your directory structure
      - 'ran/**'  # Adjust this path to match your directory structure

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: [core]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ matrix.directory }}

      - name: Validate Terraform
        run: terraform validate -no-color
        working-directory: ${{ matrix.directory }}

      - name: Plan Terraform Changes
        run: terraform plan -out=tfplan -no-color
        continue-on-error: true
        working-directory: ${{ matrix.directory }}

      - name: Apply Terraform Changes
        run: |
          export TF_LOG=DEBUG
          terraform apply -auto-approve tfplan
        continue-on-error: true
        working-directory: ${{ matrix.directory }}

      - name: Cleanup Terraform Files
        if: steps.apply.outcome == 'success'
        run: rm -f tfplan
